# Tell Spring Boot how to connect to your local MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/driving_school_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=DriveSafely@2026

# Tell Hibernate to automatically create your 'students' table based on your Entity
spring.jpa.hibernate.ddl-auto=update

# Optional: Shows the SQL queries in your console so you can see the magic happening
spring.jpa.show-sql=true